import { parseJson } from '../../util/json';

export const metadata = {
  title: 'About page',
  description: 'Generated by create next app',
};

export default function AboutPage() {
  const myComplexObject = { name: 'Karl', hobby: 'coding' };

  const myComplexObjectAsString = JSON.stringify(myComplexObject);

  const myComplexObjectAsJSAgain = parseJson(myComplexObjectAsString);

  return (
    <>
      <h1>This is my About Page</h1>
      <div>Render undefined, null, false</div>
      <div>{JSON.stringify([undefined, null, false, true])}</div>
      <div>{myComplexObjectAsString}</div>
      <div>{myComplexObjectAsJSAgain.name}</div>
      <div>{myComplexObjectAsJSAgain.hobby}</div>

      <div>This my about page</div>
    </>
  );
}
