import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { ReactNode } from 'react';
import CookieBanner from './CookieBanner';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Home page | UpLeveled',
    template: '%s | UpLeveled',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div>
            <CookieBanner />
            <nav>
              {/* This is not optimized */}
              {/* <a href="/">Home</a> */}
              {/* This is optimized */}
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/animals">Animals</Link>
              <Link href="/animals/dashboard">Dashboard</Link>
              <Link href="/fruits">Fruits</Link>
            </nav>

            {Math.floor(Math.random() * 10)}
          </div>
        </header>
        <main>{children}</main>
        <footer>Hello Footer</footer>
      </body>
    </html>
  );
}
